---
  -name: custom one action workflow

  description: This workflow is for testing the custom one action workflow

  on:
  who-to-greet:
    inputs:
        description: 'Who to greet'
        required: true
        default: 'Hello'


        outputs:
            time: Time greeted

    runs:
        using: node20
        main: dist/index.js #runs from dist at index