name: custom action workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: custom one action workflow
        uses: ./custom-one # find the folder where the custom action is located
        with:
          who-to-greet: "Hassan" # this is the input for the custom action